ajaxとjsonを使ったSPA
ilovenoah/ft_transcendence pull request #14
Opened 2024-05-25 15:11 UTC by 42rakko

ajaxとjsonを使ってSPAを実現しています
普通のページ、javascriptのページ、formのページも有効に動いています

2024-05-26 11:14 UTC, mmaekawa approved these changes

2024-05-26 14:06 UTC, kohshi54 commented
<img width="1470" alt="image" src="https://github.com/ilovenoah/ft_transcendence/assets/80312261/d6c04e26-c65f-4cce-8376-68de38a57670">
クリックしても変化しません..?

2024-05-26 14:08 UTC, kohshi54 approved these changes

2024-05-26 14:21 UTC, ilovenoah requested changes
サーバー側で動的にhtmlを返すのはspaではない気がすします

2024-05-27 04:29 UTC, 42rakko commented
> サーバー側で動的にhtmlを返すのはspaではない気がすします

discordでの議論の結果OK

2024-05-27 04:30 UTC, ilovenoah approved these changes

2024-05-27 04:33 UTC, 42rakko commented
> <img alt="image" width="1470" src="https://private-user-images.githubusercontent.com/80312261/333884972-d6c04e26-c65f-4cce-8376-68de38a57670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODQzNzAsIm5iZiI6MTcxNjc4NDA3MCwicGF0aCI6Ii84MDMxMjI2MS8zMzM4ODQ5NzItZDZjMDRlMjYtYzY1Zi00Y2NlLTgzNzYtNjhkZTM4YTU3NjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA0Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNTQwYzljZWFhMGZkNTFlNDI4NTUzYWE5MTk5YTI3ZDEyMWUzMzE0MGVkNjE2MTVlNTU5OTkyNmQ5MTgzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aubodaGnKXjf_NlOrOuUkXPGjrOQ7UdTcLulT5fk0yI"> クリックしても変化しません..?

再現性ないから、わからないわ
issueにする？

2024-05-27 13:07 UTC, 42rakko commented
マージする

2024-05-27 13:07 UTC, merged