fix/tournament
ilovenoah/ft_transcendence pull request #39
Opened 2024-06-20 15:27 UTC by mmaekawa

https://github.com/ilovenoah/ft_transcendence/issues/32

トーナメント成立時に決勝戦までの全試合をセットした
parentは現在のmatchに勝った時の次のmatch (4人のトーナメントだったら最初のmatchのparentが決勝戦)
levelは最初の試合が1、決勝戦はlog2(tournament.size)

2024-06-21 07:51 UTC, 42rakko requested changes
見ました
とりあえず４人用トーナメントを試しました
トーナメント成立時に正しくmatchmakingテーブルにレコードが作成されていました
でも、useridが一人だけしか入っていなくて、あと３人のidが登録されていません

誰と誰がマッチをするのか重要なので、なおしてください

2024-06-21 12:55 UTC, ilovenoah reviewed
ありがとうございます
見ました

2024-06-21 15:49 UTC, 42rakko approved these changes
８人用まで見ましたが、ちゃんとできていました
問題ないです
16人はさすがに大変……
最終的にチェックするか、
チェックしないなら16人トーナメントはパスしましょう

2024-06-22 01:24 UTC, ilovenoah approved these changes
ありがとうございます

2024-06-22 05:41 UTC, kohshi54 approved these changes

2024-06-22 06:03 UTC, merged