navbar
ilovenoah/ft_transcendence pull request #41
Opened 2024-07-23 12:58 UTC by mmaekawa

https://github.com/ilovenoah/ft_transcendence/issues/21

**リンクの表示適正化**
- login前
signup, login

- login後
signup, login以外 (logout、profile関連、lobby、friends関連)

**Boostrap**
navbarのみbootstrapを使ったデザインにしました

2024-07-23 14:27 UTC, 42rakko requested changes
おつかれさまです

ログイン後、login singupのリンクが消えて、logoutのリンクが出てる
ログアウト後、もとにもどる
この辺はちゃんとできていました
ありがとうございます
変更してほしいところ
・ログイン前　→　singup login　のリンクは右端に表示したいです
・ログイン後　→　logout　のリンクは右端に表示したいです
　　　　　　　　　ユーザー名のアイコンをlogoutの右に表示して、
　　　　　　　　　それをクリックすると
　　　　　　　　　[Profile][Edit Profile][Friend Request][Friends][logout]
　　　　　　　　　のリンクがプルダウン表示されるようにしてほしいです
・ログインログアウト直後　→　navbarのリンクにbootstrapが適用されてないっぽいです
　　　　　　　　　　　　　　　　classの設定がおかしいから？
　　　　　　　　　　　　　　　　
おねがいします

2024-07-23 17:11 UTC, mmaekawa commented
> おつかれさまです
> 
> ログイン後、login singupのリンクが消えて、logoutのリンクが出てる ログアウト後、もとにもどる この辺はちゃんとできていました ありがとうございます
> 
> 変更してほしいところ ・ログイン前　→　singup login　のリンクは右端に表示したいです ・ログイン後　→　ユーザーのアイコンを右端に表示して、 　　　　　　　　　それをクリックすると 　　　　　　　　　[Profile][Edit Profile][Friend Request][Friends][logout] 　　　　　　　　　のリンクがプルダウン表示されるようにしてほしいです 　　　　　　　　　　　　　　　　 おねがいします


修正しました

2024-07-24 03:17 UTC, kohshi54 commented
おつかれさまです。ありがとうございます。
- logoutもプルダウンに入れた方がいいかもしれません。
- プルダウンにEditProfileが重複して存在していました。

2024-07-24 03:50 UTC, 42rakko commented
すみません

ナイショで前のコメントを書き換えてました
やまぐちくんの言うとおり、logoutもプルダウンの一番下に入れてください

2024-07-24 05:26 UTC, 42rakko approved these changes
OKです

微妙な位置とかの細かいデザインはもっと後で直していきましょう

2024-07-24 11:48 UTC, kohshi54 approved these changes

2024-07-25 03:05 UTC, ilovenoah approved these changes
遅くなりました。
すみません

2024-07-25 13:05 UTC, merged